"""Initial memory schema

Revision ID: 0001
Revises:
Create Date: 2026-08-04

Matches docs/design/phase-1/01-memory-engine.md §4 exactly. Hand-written rather than
autogenerated: pgvector's `VECTOR` type, the partial HNSW index, and the `memory`
schema itself are all things Alembic's autogenerate cannot express without the raw
SQL this migration already uses, so there is no accuracy lost by writing it directly
against the design doc's own DDL.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS memory")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.execute(
        "CREATE TYPE memory.memory_type AS ENUM "
        "('semantic', 'procedural', 'episodic', 'project', 'preference', 'decision')"
    )
    op.execute(
        "CREATE TYPE memory.lifecycle_state AS ENUM "
        "('active', 'weak', 'archived', 'scheduled_for_deletion', 'deleted')"
    )
    op.execute(
        "CREATE TYPE memory.privacy_level AS ENUM "
        "('public', 'internal', 'confidential', 'highly_sensitive')"
    )

    op.execute(
        """
        CREATE TABLE memory.memory_record (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            memory_type memory.memory_type NOT NULL,
            content TEXT NOT NULL,
            embedding VECTOR(768),
            embedding_model TEXT,
            importance_score REAL NOT NULL DEFAULT 0.5 CHECK (importance_score BETWEEN 0 AND 1),
            confidence REAL CHECK (confidence BETWEEN 0 AND 1),
            privacy_level memory.privacy_level NOT NULL DEFAULT 'internal',
            lifecycle_state memory.lifecycle_state NOT NULL DEFAULT 'active',
            source TEXT,
            source_ref UUID,
            project_id UUID,
            user_id UUID NOT NULL,
            knowledge_node_id TEXT,
            type_data JSONB NOT NULL DEFAULT '{}',
            access_count INT NOT NULL DEFAULT 0,
            last_accessed_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            version INT NOT NULL DEFAULT 1
        )
        """
    )
    op.execute(
        "CREATE INDEX memory_record_embedding_hnsw ON memory.memory_record "
        "USING hnsw (embedding vector_cosine_ops) WHERE embedding IS NOT NULL"
    )
    op.execute("CREATE INDEX memory_record_type_idx ON memory.memory_record (memory_type)")
    op.execute(
        "CREATE INDEX memory_record_project_idx ON memory.memory_record (project_id) "
        "WHERE project_id IS NOT NULL"
    )
    op.execute(
        "CREATE INDEX memory_record_lifecycle_idx ON memory.memory_record (lifecycle_state)"
    )
    op.execute("CREATE INDEX memory_record_user_idx ON memory.memory_record (user_id)")
    op.execute(
        "CREATE INDEX memory_record_type_data_gin ON memory.memory_record USING gin (type_data)"
    )
    op.execute(
        "CREATE INDEX memory_record_created_at_idx ON memory.memory_record (created_at DESC)"
    )

    op.execute(
        """
        CREATE TABLE memory.short_term_record (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            content TEXT NOT NULL,
            category TEXT NOT NULL,
            project_id UUID,
            user_id UUID NOT NULL,
            source_ref UUID,
            expires_at TIMESTAMPTZ NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute("CREATE INDEX short_term_expires_idx ON memory.short_term_record (expires_at)")
    op.execute(
        "CREATE INDEX short_term_user_idx ON memory.short_term_record (user_id, created_at DESC)"
    )

    op.execute(
        """
        CREATE TABLE memory.decision_record (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            memory_record_id UUID NOT NULL REFERENCES memory.memory_record(id) ON DELETE CASCADE,
            objective TEXT NOT NULL,
            alternatives JSONB NOT NULL DEFAULT '[]',
            chosen_alternative TEXT NOT NULL,
            reasoning TEXT NOT NULL,
            tradeoffs JSONB NOT NULL DEFAULT '[]',
            risks JSONB NOT NULL DEFAULT '[]',
            outcome TEXT,
            outcome_recorded_at TIMESTAMPTZ,
            confidence_at_decision REAL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )

    op.execute(
        """
        CREATE TABLE memory.consolidation_run (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            finished_at TIMESTAMPTZ,
            records_scanned INT,
            records_merged INT,
            records_advanced INT,
            records_deleted INT,
            status TEXT NOT NULL DEFAULT 'running'
        )
        """
    )

    op.execute(
        """
        CREATE TABLE memory.audit_log (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            memory_record_id UUID NOT NULL,
            action TEXT NOT NULL,
            actor TEXT NOT NULL,
            changed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            detail JSONB
        )
        """
    )

    op.execute(
        """
        CREATE TABLE memory.outbox_event (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            subject TEXT NOT NULL,
            payload JSONB NOT NULL,
            correlation_id UUID NOT NULL,
            causation_id UUID,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            dispatched_at TIMESTAMPTZ
        )
        """
    )
    op.execute(
        "CREATE INDEX outbox_undispatched_idx ON memory.outbox_event (created_at) "
        "WHERE dispatched_at IS NULL"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS memory.outbox_event")
    op.execute("DROP TABLE IF EXISTS memory.audit_log")
    op.execute("DROP TABLE IF EXISTS memory.consolidation_run")
    op.execute("DROP TABLE IF EXISTS memory.decision_record")
    op.execute("DROP TABLE IF EXISTS memory.short_term_record")
    op.execute("DROP TABLE IF EXISTS memory.memory_record")
    op.execute("DROP TYPE IF EXISTS memory.privacy_level")
    op.execute("DROP TYPE IF EXISTS memory.lifecycle_state")
    op.execute("DROP TYPE IF EXISTS memory.memory_type")
    op.execute("DROP SCHEMA IF EXISTS memory CASCADE")
