"""Initial cognitive_state schema

Revision ID: 0001
Revises:
Create Date: 2026-09-15

`cognitive_state.active_thought` matches
`docs/design/phase-4/06-tdd-4f-companion-and-cognitive-state.md` §13 and Bible
Part 6's *"Each thought should have"* list. Hand-written rather than
autogenerated, the same convention as every prior engine's initial migration,
and matching `repository/models.py` column for column.

**Additive only.** This migration creates a new schema and touches no existing
engine's tables. `action.identity_confidence_policy` in particular is untouched
in structure *and* in content -- CF-9 is a Phase 4F dependency but it is
**4F.4's** work in `action-engine`, its owning engine, and 4F.1 writes no policy
row anywhere (TDD 4F §5.2, D-4D-2).

**One table.** Focus is derived, not stored (`domain/focus.py`), and an
Attention Layer is a column on a thought rather than an entity. TDD 4F's scope
rule for 4F.1 forbids speculative tables for later slices, so there are none
here for the trigger (4F.6) or the panel (4F.7).
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS cognitive_state")

    op.execute(
        """
        CREATE TABLE cognitive_state.active_thought (
            thought_id            UUID PRIMARY KEY,
            user_id               UUID NOT NULL,
            description           TEXT NOT NULL,
            priority              INTEGER NOT NULL,
            confidence            DOUBLE PRECISION NOT NULL,
            current_progress      DOUBLE PRECISION NOT NULL,
            dependencies          JSONB NOT NULL DEFAULT '[]'::jsonb,
            related_memories      JSONB NOT NULL DEFAULT '[]'::jsonb,
            related_projects      JSONB NOT NULL DEFAULT '[]'::jsonb,
            estimated_completion  TIMESTAMPTZ,
            attention_layer       TEXT NOT NULL,
            created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT ck_active_thought_confidence_range
                CHECK (confidence >= 0.0 AND confidence <= 1.0),
            CONSTRAINT ck_active_thought_progress_range
                CHECK (current_progress >= 0.0 AND current_progress <= 1.0),
            CONSTRAINT ck_active_thought_priority_non_negative
                CHECK (priority >= 0)
        )
        """
    )

    # Two access paths the panel and the Focus System actually use: "everything
    # in this layer" and "what changed most recently". Neither is speculative --
    # `list_thoughts` issues exactly these two shapes.
    op.execute(
        """
        CREATE INDEX ix_active_thought_user_layer
            ON cognitive_state.active_thought (user_id, attention_layer)
        """
    )
    op.execute(
        """
        CREATE INDEX ix_active_thought_user_updated
            ON cognitive_state.active_thought (user_id, updated_at)
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS cognitive_state.active_thought")
    op.execute("DROP SCHEMA IF EXISTS cognitive_state")
