"""Initial communication schema

Revision ID: 0001
Revises:
Create Date: 2026-08-07

Matches docs/design/phase-2d/01-communication-engine.md Sec10 exactly (plus
the transactional outbox table every prior engine's own initial migration
adds, since this engine publishes four event types unlike personality-engine).
Hand-written rather than autogenerated, the same convention as every prior
engine's initial migration.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS communication")

    op.execute(
        """
        CREATE TABLE communication.conversation_session (
            session_id        UUID PRIMARY KEY,
            user_id            UUID NOT NULL,
            channel            TEXT NOT NULL,
            device_id          UUID NOT NULL,
            state              TEXT NOT NULL,
            objective          TEXT,
            pending_questions  JSONB,
            created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
            closed_at          TIMESTAMPTZ
        )
        """
    )

    op.execute(
        """
        CREATE TABLE communication.conversation_turn (
            turn_id                 UUID PRIMARY KEY,
            session_id              UUID NOT NULL REFERENCES communication.conversation_session,
            direction                TEXT NOT NULL,
            content                  TEXT NOT NULL,
            channel                  TEXT NOT NULL,
            personality_validated    BOOLEAN,
            created_at                TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute(
        "CREATE INDEX conversation_turn_session_idx "
        "ON communication.conversation_turn (session_id)"
    )

    op.execute(
        """
        CREATE TABLE communication.notification (
            notification_id  UUID PRIMARY KEY,
            user_id           UUID NOT NULL,
            content           TEXT NOT NULL,
            priority          TEXT NOT NULL,
            delivered_at      TIMESTAMPTZ,
            created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute(
        "CREATE INDEX notification_user_idx ON communication.notification (user_id)"
    )

    op.execute(
        """
        CREATE TABLE communication.outbox_event (
            id                UUID PRIMARY KEY,
            subject           TEXT NOT NULL,
            payload           JSONB NOT NULL,
            correlation_id    UUID NOT NULL,
            causation_id      UUID,
            created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
            dispatched_at     TIMESTAMPTZ
        )
        """
    )
    op.execute(
        "CREATE INDEX outbox_event_dispatch_ready_idx "
        "ON communication.outbox_event (created_at) WHERE dispatched_at IS NULL"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS communication.outbox_event")
    op.execute("DROP TABLE IF EXISTS communication.notification")
    op.execute("DROP TABLE IF EXISTS communication.conversation_turn")
    op.execute("DROP TABLE IF EXISTS communication.conversation_session")
    op.execute("DROP SCHEMA IF EXISTS communication CASCADE")
