"""Initial model_orchestration schema

Revision ID: 0001
Revises:
Create Date: 2026-08-05

Matches docs/design/phase-2a/00-ai-model-orchestration-engine.md §4 exactly.
Hand-written rather than autogenerated, the same convention as every Phase 1
engine's initial migration. No `graph_write`/`graph_applied_at` columns on
`outbox_event` -- this engine owns no graph (§4: nothing in Bible Part 7 calls
for one).
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS model_orchestration")

    op.execute(
        """
        CREATE TABLE model_orchestration.model_registry (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            name TEXT NOT NULL,
            version TEXT NOT NULL,
            provider TEXT NOT NULL,
            connector_type TEXT NOT NULL,
            is_local BOOLEAN NOT NULL,
            modalities JSONB NOT NULL,
            capability_scores JSONB NOT NULL,
            context_window INTEGER NOT NULL,
            max_output_tokens INTEGER NOT NULL,
            avg_latency_ms DOUBLE PRECISION,
            avg_quality_score DOUBLE PRECISION,
            hardware_requirements JSONB NOT NULL DEFAULT '{}'::jsonb,
            license TEXT,
            cost_per_input_token NUMERIC(12, 8),
            cost_per_output_token NUMERIC(12, 8),
            max_privacy_tier TEXT NOT NULL,
            health_status TEXT NOT NULL DEFAULT 'unknown',
            schema_version INTEGER NOT NULL DEFAULT 1,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            UNIQUE (name, version, provider)
        )
        """
    )

    op.execute(
        """
        CREATE TABLE model_orchestration.model_health_snapshot (
            id BIGSERIAL PRIMARY KEY,
            model_id UUID NOT NULL REFERENCES model_orchestration.model_registry(id),
            checked_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            available BOOLEAN NOT NULL,
            latency_ms DOUBLE PRECISION,
            error_rate DOUBLE PRECISION
        )
        """
    )
    op.execute(
        "CREATE INDEX health_snapshot_model_idx ON model_orchestration.model_health_snapshot "
        "(model_id, checked_at DESC)"
    )

    op.execute(
        """
        CREATE TABLE model_orchestration.usage_record (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            correlation_id UUID NOT NULL,
            requesting_engine TEXT NOT NULL,
            provider TEXT NOT NULL,
            model_id UUID NOT NULL REFERENCES model_orchestration.model_registry(id),
            routing_decision JSONB NOT NULL,
            estimated_complexity DOUBLE PRECISION NOT NULL,
            latency_ms DOUBLE PRECISION NOT NULL,
            input_tokens INTEGER NOT NULL,
            output_tokens INTEGER NOT NULL,
            estimated_cost NUMERIC(12, 6) NOT NULL,
            retry_count INTEGER NOT NULL DEFAULT 0,
            fallback_used BOOLEAN NOT NULL DEFAULT false,
            privacy_classification TEXT NOT NULL,
            outcome TEXT NOT NULL,
            schema_version INTEGER NOT NULL DEFAULT 1,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute(
        "CREATE INDEX usage_correlation_idx ON model_orchestration.usage_record (correlation_id)"
    )
    op.execute(
        "CREATE INDEX usage_model_time_idx ON model_orchestration.usage_record "
        "(model_id, created_at DESC)"
    )

    op.execute(
        """
        CREATE TABLE model_orchestration.budget (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            scope TEXT NOT NULL,
            scope_ref TEXT,
            period TEXT NOT NULL DEFAULT 'monthly',
            limit_amount NUMERIC(12, 2) NOT NULL,
            currency TEXT NOT NULL DEFAULT 'USD',
            alert_threshold_pct INTEGER NOT NULL DEFAULT 80
        )
        """
    )

    op.execute(
        """
        CREATE TABLE model_orchestration.outbox_event (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            subject TEXT NOT NULL,
            payload JSONB NOT NULL,
            correlation_id UUID NOT NULL,
            causation_id UUID,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            dispatched_at TIMESTAMPTZ
        )
        """
    )
    op.execute(
        "CREATE INDEX outbox_undispatched_idx ON model_orchestration.outbox_event (created_at) "
        "WHERE dispatched_at IS NULL"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS model_orchestration.outbox_event")
    op.execute("DROP TABLE IF EXISTS model_orchestration.budget")
    op.execute("DROP TABLE IF EXISTS model_orchestration.usage_record")
    op.execute("DROP TABLE IF EXISTS model_orchestration.model_health_snapshot")
    op.execute("DROP TABLE IF EXISTS model_orchestration.model_registry")
    op.execute("DROP SCHEMA IF EXISTS model_orchestration CASCADE")
