"""Initial capability schema

Revision ID: 0001
Revises:
Create Date: 2026-08-16

Matches docs/design/phase-3/06-tdd-3c-capability-engine.md §6 exactly.
Hand-written rather than autogenerated, the same convention as every prior
engine's initial migration.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS capability")

    op.execute(
        """
        CREATE TABLE capability.capability (
            id                         UUID PRIMARY KEY,
            name                       TEXT NOT NULL,
            description                TEXT NOT NULL,
            category                   TEXT NOT NULL,
            version                    TEXT NOT NULL,
            dependencies               JSONB NOT NULL DEFAULT '[]',
            required_permissions       JSONB NOT NULL,
            required_resources         JSONB NOT NULL DEFAULT '[]',
            input_schema               JSONB NOT NULL,
            output_schema              JSONB NOT NULL,
            execution_adapter          TEXT NOT NULL,
            health_status              TEXT NOT NULL DEFAULT 'unknown',
            installed_at               TIMESTAMPTZ NOT NULL,
            permissions_reviewed_at    TIMESTAMPTZ,
            sandbox_test_passed_at     TIMESTAMPTZ,
            UNIQUE (name, version)
        )
        """
    )

    op.execute(
        """
        CREATE TABLE capability.capability_installation_event (
            id                UUID PRIMARY KEY,
            capability_id     UUID,
            name              TEXT NOT NULL,
            version           TEXT NOT NULL,
            stage             TEXT NOT NULL,
            outcome           TEXT NOT NULL,
            detail            TEXT,
            created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute(
        "CREATE INDEX capability_installation_event_capability_idx "
        "ON capability.capability_installation_event (capability_id)"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS capability.capability_installation_event")
    op.execute("DROP TABLE IF EXISTS capability.capability")
    op.execute("DROP SCHEMA IF EXISTS capability")
