"""Initial personality schema

Revision ID: 0001
Revises:
Create Date: 2026-08-07

Matches docs/design/phase-2d/02-personality-engine.md Sec9 exactly. Hand-written
rather than autogenerated, the same convention as every prior engine's initial
migration.

Seeds the singleton `core_identity` row directly from Doc 23 (NOVA Personality
Specification) Sec2 and Sec6 -- this is the deployment-time configuration
change Doc 23's own closing section and this engine's design doc Sec14
describe as the only legal way `core_identity` ever changes (never a runtime
API). Also seeds the singleton `memory_profile` row with its documented
static default (design doc Sec6) so `get_memory_profile()` never needs a
null-row fallback in ordinary operation.
"""

from __future__ import annotations

import json
from collections.abc import Sequence

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None

# Doc 23 Sec2 "Core Identity" -- the twelve constant traits, verbatim.
_TRAITS = [
    "calm",
    "professional",
    "respectful",
    "curious",
    "reliable",
    "patient",
    "confident",
    "analytical",
    "honest",
    "supportive",
    "focused",
    "consistent",
]

# Doc 23 Sec2 "Fundamental values" -- Trust Before Intelligence listed first
# per its own standing-directive text ("the tiebreaker above the other
# tiebreakers"), followed by the original eight, verbatim.
_VALUES = [
    "Trust Before Intelligence",
    "Truth over appearance",
    "Transparency over certainty",
    "Evidence over assumptions",
    "Clarity over complexity",
    "Safety over speed",
    "Learning over ego",
    "Respect over persuasion",
    "Helping over impressing",
]

# Doc 23 Sec6 "Permanently forbidden behaviors", short slugs matching the
# validator's own check-family naming style.
_FORBIDDEN_BEHAVIORS = [
    "manipulation",
    "unnecessary_interruptions",
    "pretending_certainty_when_uncertain",
    "inventing_memories_or_facts",
    "emotional_pressure",
    "influencing_decisions_outside_user_interests",
    "claiming_capability_not_had",
    "silent_identity_assumption",
    "defensiveness_sarcasm_or_impatience",
]

_VERSION_NOTE = (
    "Doc 23 (NOVA Personality Specification) as approved, "
    "including the five standing directives."
)


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS personality")

    op.execute(
        """
        CREATE TABLE personality.core_identity (
            id INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),
            schema_version INTEGER NOT NULL DEFAULT 1,
            traits JSONB NOT NULL,
            values JSONB NOT NULL,
            forbidden_behaviors JSONB NOT NULL,
            version_note TEXT NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )

    op.execute(
        """
        CREATE TABLE personality.memory_profile (
            id INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),
            verbosity TEXT NOT NULL DEFAULT 'moderate',
            technical_depth TEXT NOT NULL DEFAULT 'moderate',
            terminology_preference JSONB,
            source TEXT NOT NULL DEFAULT 'static_default',
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )

    op.execute(
        """
        CREATE TABLE personality.validation_audit (
            audit_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            session_id UUID NOT NULL,
            passed BOOLEAN NOT NULL,
            violations JSONB,
            selected_style TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute(
        "CREATE INDEX validation_audit_session_idx ON personality.validation_audit (session_id)"
    )
    op.execute(
        "CREATE INDEX validation_audit_created_idx ON personality.validation_audit (created_at)"
    )

    op.execute(
        f"""
        INSERT INTO personality.core_identity
            (id, schema_version, traits, values, forbidden_behaviors, version_note)
        VALUES (
            1,
            1,
            '{json.dumps(_TRAITS)}'::jsonb,
            '{json.dumps(_VALUES)}'::jsonb,
            '{json.dumps(_FORBIDDEN_BEHAVIORS)}'::jsonb,
            '{_VERSION_NOTE}'
        )
        """
    )
    op.execute(
        """
        INSERT INTO personality.memory_profile (id, verbosity, technical_depth, source)
        VALUES (1, 'moderate', 'moderate', 'static_default')
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS personality.validation_audit")
    op.execute("DROP TABLE IF EXISTS personality.memory_profile")
    op.execute("DROP TABLE IF EXISTS personality.core_identity")
    op.execute("DROP SCHEMA IF EXISTS personality CASCADE")
