"""Initial world_model schema

Revision ID: 0001
Revises:
Create Date: 2026-08-04

Matches docs/design/phase-1/03-world-model-engine.md §4 exactly. Hand-written
rather than autogenerated: the `world_model` schema itself is something
Alembic's autogenerate cannot express without the raw SQL this migration
already uses, so there is no accuracy lost by writing it directly against the
design doc's own DDL. No `vector` extension, no `VECTOR` columns anywhere --
§10: World Model Engine does not embed.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS world_model")

    op.execute(
        """
        CREATE TABLE world_model.object_state_history (
            id BIGSERIAL PRIMARY KEY,
            object_id TEXT NOT NULL,
            object_label TEXT NOT NULL,
            user_id UUID NOT NULL,
            previous_state TEXT,
            new_state TEXT NOT NULL,
            confidence REAL,
            changed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            correlation_id UUID
        )
        """
    )
    op.execute(
        "CREATE INDEX osh_object_idx ON world_model.object_state_history "
        "(object_id, changed_at DESC)"
    )
    op.execute(
        "CREATE INDEX osh_user_idx ON world_model.object_state_history "
        "(user_id, changed_at DESC)"
    )

    op.execute(
        """
        CREATE TABLE world_model.snapshot (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            user_id UUID NOT NULL,
            taken_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            snapshot_data JSONB NOT NULL,
            trigger TEXT NOT NULL
        )
        """
    )
    op.execute("CREATE INDEX snapshot_user_idx ON world_model.snapshot (user_id, taken_at DESC)")

    op.execute(
        """
        CREATE TABLE world_model.prediction (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            user_id UUID NOT NULL,
            prediction TEXT NOT NULL,
            confidence REAL NOT NULL,
            predicted_for TIMESTAMPTZ,
            outcome TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )

    op.execute(
        """
        CREATE TABLE world_model.conflict_log (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            object_id TEXT NOT NULL,
            observation_a JSONB NOT NULL,
            observation_b JSONB NOT NULL,
            resolution_strategy TEXT NOT NULL,
            resolved_value JSONB,
            resolved_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )

    op.execute(
        """
        CREATE TABLE world_model.outbox_event (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            subject TEXT NOT NULL,
            payload JSONB NOT NULL,
            correlation_id UUID NOT NULL,
            causation_id UUID,
            graph_write JSONB,
            graph_applied_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            dispatched_at TIMESTAMPTZ
        )
        """
    )
    op.execute(
        "CREATE INDEX outbox_undispatched_idx ON world_model.outbox_event (created_at) "
        "WHERE dispatched_at IS NULL"
    )
    op.execute(
        "CREATE INDEX outbox_graph_pending_idx ON world_model.outbox_event (created_at) "
        "WHERE graph_write IS NOT NULL AND graph_applied_at IS NULL"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS world_model.outbox_event")
    op.execute("DROP TABLE IF EXISTS world_model.conflict_log")
    op.execute("DROP TABLE IF EXISTS world_model.prediction")
    op.execute("DROP TABLE IF EXISTS world_model.snapshot")
    op.execute("DROP TABLE IF EXISTS world_model.object_state_history")
    op.execute("DROP SCHEMA IF EXISTS world_model CASCADE")
