"""Initial reasoning schema

Revision ID: 0001
Revises:
Create Date: 2026-08-05

Matches docs/design/phase-2b/00-reasoning-engine.md §20 exactly. Hand-written
rather than autogenerated, the same convention as every prior engine's
initial migration. No `graph_write`/`graph_applied_at` columns on
`outbox_event` -- this engine owns no graph.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS reasoning")

    op.execute(
        """
        CREATE TABLE reasoning.reasoning_process (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            correlation_id UUID NOT NULL,
            requesting_engine TEXT NOT NULL,
            user_id UUID NOT NULL,
            parent_process_id UUID REFERENCES reasoning.reasoning_process(id),
            objective_text TEXT NOT NULL,
            reasoning_mode TEXT NOT NULL,
            reasoning_level INTEGER NOT NULL,
            status TEXT NOT NULL DEFAULT 'received',
            schema_version INTEGER NOT NULL DEFAULT 1,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            completed_at TIMESTAMPTZ
        )
        """
    )
    op.execute(
        "CREATE INDEX reasoning_process_parent_idx ON reasoning.reasoning_process "
        "(parent_process_id)"
    )
    op.execute(
        "CREATE INDEX reasoning_process_correlation_idx ON reasoning.reasoning_process "
        "(correlation_id)"
    )
    op.execute(
        "CREATE INDEX reasoning_process_user_idx ON reasoning.reasoning_process (user_id)"
    )

    op.execute(
        """
        CREATE TABLE reasoning.hypothesis (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            reasoning_process_id UUID NOT NULL REFERENCES reasoning.reasoning_process(id),
            description TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'investigating',
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute(
        "CREATE INDEX hypothesis_process_idx ON reasoning.hypothesis (reasoning_process_id)"
    )

    op.execute(
        """
        CREATE TABLE reasoning.evidence (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            hypothesis_id UUID NOT NULL REFERENCES reasoning.hypothesis(id),
            source TEXT NOT NULL,
            source_ref TEXT NOT NULL,
            weight DOUBLE PRECISION NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute("CREATE INDEX evidence_hypothesis_idx ON reasoning.evidence (hypothesis_id)")

    op.execute(
        """
        CREATE TABLE reasoning.alternative (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            reasoning_process_id UUID NOT NULL REFERENCES reasoning.reasoning_process(id),
            hypothesis_id UUID NOT NULL REFERENCES reasoning.hypothesis(id),
            description TEXT NOT NULL,
            constraint_status TEXT NOT NULL,
            matrix_scores JSONB,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute(
        "CREATE INDEX alternative_process_idx ON reasoning.alternative (reasoning_process_id)"
    )

    op.execute(
        """
        CREATE TABLE reasoning.decision (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            reasoning_process_id UUID NOT NULL REFERENCES reasoning.reasoning_process(id),
            selected_alternative_id UUID REFERENCES reasoning.alternative(id),
            explanation JSONB NOT NULL,
            confidence_score DOUBLE PRECISION NOT NULL,
            human_override JSONB,
            schema_version INTEGER NOT NULL DEFAULT 1,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute("CREATE INDEX decision_process_idx ON reasoning.decision (reasoning_process_id)")

    op.execute(
        """
        CREATE TABLE reasoning.reasoning_trace (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            reasoning_process_id UUID NOT NULL REFERENCES reasoning.reasoning_process(id),
            trace_payload JSONB NOT NULL,
            schema_version INTEGER NOT NULL DEFAULT 1,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute(
        "CREATE INDEX reasoning_trace_process_idx ON reasoning.reasoning_trace "
        "(reasoning_process_id)"
    )

    op.execute(
        """
        CREATE TABLE reasoning.outbox_event (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            subject TEXT NOT NULL,
            payload JSONB NOT NULL,
            correlation_id UUID NOT NULL,
            causation_id UUID,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            dispatched_at TIMESTAMPTZ
        )
        """
    )
    op.execute(
        "CREATE INDEX outbox_undispatched_idx ON reasoning.outbox_event (created_at) "
        "WHERE dispatched_at IS NULL"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS reasoning.outbox_event")
    op.execute("DROP TABLE IF EXISTS reasoning.reasoning_trace")
    op.execute("DROP TABLE IF EXISTS reasoning.decision")
    op.execute("DROP TABLE IF EXISTS reasoning.alternative")
    op.execute("DROP TABLE IF EXISTS reasoning.evidence")
    op.execute("DROP TABLE IF EXISTS reasoning.hypothesis")
    op.execute("DROP TABLE IF EXISTS reasoning.reasoning_process")
    op.execute("DROP SCHEMA IF EXISTS reasoning CASCADE")
