"""Initial action schema

Revision ID: 0001
Revises:
Create Date: 2026-08-17

Matches docs/design/phase-3/07-tdd-3d-action-engine.md §8 exactly.
Hand-written rather than autogenerated, the same convention as every prior
engine's initial migration.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS action")

    op.execute(
        """
        CREATE TABLE action.action (
            id                      UUID PRIMARY KEY,
            action_type             TEXT NOT NULL,
            priority                TEXT NOT NULL,
            source                  TEXT NOT NULL,
            requested_by            UUID NOT NULL,
            execution_target        TEXT NOT NULL,
            depends_on              JSONB NOT NULL DEFAULT '[]',
            parameters              JSONB NOT NULL DEFAULT '{}',
            expected_result         TEXT,
            risk                    TEXT NOT NULL,
            timeout_seconds         INTEGER NOT NULL,
            retry_policy            JSONB NOT NULL,
            rollback_strategy       JSONB,
            required_permissions    JSONB NOT NULL DEFAULT '[]',
            status                  TEXT NOT NULL DEFAULT 'pending',
            verification_method     TEXT NOT NULL,
            confidence              DOUBLE PRECISION,
            result                  JSONB,
            error                   TEXT,
            created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )

    op.execute(
        """
        CREATE TABLE action.pending_approval (
            action_id     UUID PRIMARY KEY REFERENCES action.action (id),
            risk          TEXT NOT NULL,
            requested_at  TIMESTAMPTZ NOT NULL,
            decided_at    TIMESTAMPTZ,
            decision      TEXT
        )
        """
    )

    op.execute(
        """
        CREATE TABLE action.action_execution_history (
            id          UUID PRIMARY KEY,
            action_id   UUID NOT NULL,
            stage       TEXT NOT NULL,
            outcome     TEXT NOT NULL,
            detail      TEXT,
            created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute(
        "CREATE INDEX action_execution_history_action_idx "
        "ON action.action_execution_history (action_id)"
    )

    op.execute(
        """
        CREATE TABLE action.identity_confidence_policy (
            user_id                       UUID PRIMARY KEY,
            minimum_confidence_by_risk    JSONB NOT NULL
        )
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS action.identity_confidence_policy")
    op.execute("DROP TABLE IF EXISTS action.action_execution_history")
    op.execute("DROP TABLE IF EXISTS action.pending_approval")
    op.execute("DROP TABLE IF EXISTS action.action")
    op.execute("DROP SCHEMA IF EXISTS action")
