"""Initial digital_twin schema

Revision ID: 0001
Revises:
Create Date: 2026-08-11

Matches docs/design/phase-2d/06-personal-companion.md Sec11.1 exactly
(plus `completed_session_evidence`, an implementation-time addition --
`domain/ports.py`'s own module docstring explains why -- and the
transactional outbox table every prior publishing engine's own initial
migration adds). Hand-written rather than autogenerated, the same
convention as every prior engine's initial migration.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS digital_twin")

    op.execute(
        """
        CREATE TABLE digital_twin.communication_profile (
            user_id                    UUID PRIMARY KEY,
            verbosity                   TEXT NOT NULL DEFAULT 'moderate',
            technical_depth              TEXT NOT NULL DEFAULT 'moderate',
            terminology_preference        JSONB,
            conversation_pacing            TEXT,
            habit_timing_hint               TEXT,
            source                            TEXT NOT NULL DEFAULT 'static_default',
            updated_at                          TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )

    op.execute(
        """
        CREATE TABLE digital_twin.preference_evolution_history (
            id                UUID PRIMARY KEY,
            user_id            UUID NOT NULL,
            field               TEXT NOT NULL,
            previous_value       TEXT,
            new_value              TEXT NOT NULL,
            confidence              REAL NOT NULL,
            source                    TEXT NOT NULL,
            reason                     TEXT NOT NULL,
            changed_at                  TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute(
        "CREATE INDEX preference_evolution_history_user_idx "
        "ON digital_twin.preference_evolution_history (user_id, changed_at)"
    )

    op.execute(
        """
        CREATE TABLE digital_twin.habit_signal (
            id                          UUID PRIMARY KEY,
            user_id                      UUID NOT NULL,
            session_id                    UUID NOT NULL,
            turn_count                      INT NOT NULL,
            session_duration_seconds          REAL,
            observed_at                          TIMESTAMPTZ NOT NULL
        )
        """
    )
    op.execute(
        "CREATE INDEX habit_signal_user_idx ON digital_twin.habit_signal (user_id, observed_at)"
    )

    op.execute(
        """
        CREATE TABLE digital_twin.completed_session_evidence (
            session_id       UUID PRIMARY KEY,
            user_id           UUID NOT NULL,
            turn_count         INT NOT NULL,
            corrections          JSONB NOT NULL DEFAULT '[]'::jsonb,
            preferences            JSONB NOT NULL DEFAULT '[]'::jsonb,
            feedback                 JSONB NOT NULL DEFAULT '[]'::jsonb,
            decisions                  JSONB NOT NULL DEFAULT '[]'::jsonb,
            closed_at                    TIMESTAMPTZ NOT NULL
        )
        """
    )
    op.execute(
        "CREATE INDEX completed_session_evidence_user_idx "
        "ON digital_twin.completed_session_evidence (user_id, closed_at)"
    )

    op.execute(
        """
        CREATE TABLE digital_twin.trust_metric (
            user_id                                  UUID PRIMARY KEY,
            correction_frequency                      REAL,
            window_session_count                        INT NOT NULL DEFAULT 0,
            clarification_acceptance_rate                 REAL,
            proactive_suggestion_acceptance_rate            REAL,
            computed_at                                       TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )

    op.execute(
        """
        CREATE TABLE digital_twin.trust_metric_history (
            id                    UUID PRIMARY KEY,
            user_id                UUID NOT NULL,
            correction_frequency     REAL,
            window_session_count       INT NOT NULL,
            computed_at                   TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute(
        "CREATE INDEX trust_metric_history_user_idx "
        "ON digital_twin.trust_metric_history (user_id, computed_at)"
    )

    op.execute(
        """
        CREATE TABLE digital_twin.proactive_boundary_policy (
            user_id                     UUID PRIMARY KEY,
            enabled                      BOOLEAN NOT NULL DEFAULT true,
            max_per_topic_per_window       JSONB NOT NULL DEFAULT '{}'::jsonb,
            window_hours                      INT NOT NULL DEFAULT 24
        )
        """
    )

    op.execute(
        """
        CREATE TABLE digital_twin.outbox_event (
            id                UUID PRIMARY KEY,
            subject           TEXT NOT NULL,
            payload           JSONB NOT NULL,
            correlation_id    UUID NOT NULL,
            causation_id      UUID,
            created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
            dispatched_at     TIMESTAMPTZ
        )
        """
    )
    op.execute(
        "CREATE INDEX outbox_event_dispatch_ready_idx "
        "ON digital_twin.outbox_event (created_at) WHERE dispatched_at IS NULL"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS digital_twin.outbox_event")
    op.execute("DROP TABLE IF EXISTS digital_twin.proactive_boundary_policy")
    op.execute("DROP TABLE IF EXISTS digital_twin.trust_metric_history")
    op.execute("DROP TABLE IF EXISTS digital_twin.trust_metric")
    op.execute("DROP TABLE IF EXISTS digital_twin.completed_session_evidence")
    op.execute("DROP TABLE IF EXISTS digital_twin.habit_signal")
    op.execute("DROP TABLE IF EXISTS digital_twin.preference_evolution_history")
    op.execute("DROP TABLE IF EXISTS digital_twin.communication_profile")
    op.execute("DROP SCHEMA IF EXISTS digital_twin CASCADE")
