"""Initial perception schema

Revision ID: 0001
Revises:
Create Date: 2026-08-07

Matches docs/design/phase-2d/03-perception-engine.md Sec15 exactly (plus the
transactional outbox table every prior publishing engine's own initial
migration adds). Hand-written rather than autogenerated, the same convention
as every prior engine's initial migration.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS perception")

    op.execute(
        """
        CREATE TABLE perception.enrolled_identity (
            identity_id           UUID PRIMARY KEY,
            user_id                UUID NOT NULL,
            modality               TEXT NOT NULL,
            template_ciphertext    BYTEA NOT NULL,
            enrolled_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
            revoked_at              TIMESTAMPTZ
        )
        """
    )
    op.execute(
        "CREATE INDEX enrolled_identity_user_idx ON perception.enrolled_identity (user_id)"
    )

    op.execute(
        """
        CREATE TABLE perception.consent_grant (
            consent_id       UUID PRIMARY KEY,
            user_id           UUID NOT NULL,
            source            TEXT NOT NULL,
            scope             TEXT NOT NULL,
            granted_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
            revoked_at         TIMESTAMPTZ
        )
        """
    )
    op.execute(
        "CREATE INDEX consent_grant_user_source_idx "
        "ON perception.consent_grant (user_id, source)"
    )

    op.execute(
        """
        CREATE TABLE perception.identity_observation (
            observation_id       UUID PRIMARY KEY,
            user_id                UUID NOT NULL,
            identity_id            UUID REFERENCES perception.enrolled_identity,
            fused_confidence        REAL NOT NULL,
            confidence_tier          TEXT NOT NULL,
            per_modality_signals     JSONB NOT NULL,
            correlation_id            UUID,
            observed_at                TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute(
        "CREATE INDEX identity_observation_user_idx "
        "ON perception.identity_observation (user_id, observed_at)"
    )

    op.execute(
        """
        CREATE TABLE perception.sensor_registration (
            sensor_id         TEXT PRIMARY KEY,
            sensor_type        TEXT NOT NULL,
            status              TEXT NOT NULL,
            capabilities         JSONB NOT NULL,
            last_health_check_at  TIMESTAMPTZ,
            error_count            INT NOT NULL DEFAULT 0
        )
        """
    )

    op.execute(
        """
        CREATE TABLE perception.outbox_event (
            id                UUID PRIMARY KEY,
            subject           TEXT NOT NULL,
            payload           JSONB NOT NULL,
            correlation_id    UUID NOT NULL,
            causation_id      UUID,
            created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
            dispatched_at     TIMESTAMPTZ
        )
        """
    )
    op.execute(
        "CREATE INDEX outbox_event_dispatch_ready_idx "
        "ON perception.outbox_event (created_at) WHERE dispatched_at IS NULL"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS perception.outbox_event")
    op.execute("DROP TABLE IF EXISTS perception.sensor_registration")
    op.execute("DROP TABLE IF EXISTS perception.identity_observation")
    op.execute("DROP TABLE IF EXISTS perception.consent_grant")
    op.execute("DROP TABLE IF EXISTS perception.enrolled_identity")
    op.execute("DROP SCHEMA IF EXISTS perception CASCADE")
