"""Initial knowledge schema

Revision ID: 0001
Revises:
Create Date: 2026-08-04

Matches docs/design/phase-1/02-knowledge-engine.md §4, plus one justified
extension (`knowledge.node_usage` -- see `repository/models.py`'s
`NodeUsageORM` docstring). Hand-written rather than autogenerated: pgvector's
`VECTOR` type, the partial HNSW index, and the `knowledge` schema itself are all
things Alembic's autogenerate cannot express without the raw SQL this migration
already uses, so there is no accuracy lost by writing it directly against the
design doc's own DDL.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS knowledge")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.execute(
        "CREATE TYPE knowledge.layer AS ENUM "
        "('raw', 'processed', 'verified', 'connected', 'applied', 'expert', 'strategic')"
    )
    op.execute(
        "CREATE TYPE knowledge.privacy_level AS ENUM "
        "('public', 'internal', 'confidential', 'highly_sensitive')"
    )

    op.execute(
        """
        CREATE TABLE knowledge.node_metadata (
            node_id TEXT PRIMARY KEY,
            label TEXT NOT NULL,
            name TEXT NOT NULL,
            domain TEXT,
            scope TEXT NOT NULL DEFAULT 'global',
            project_id UUID,
            user_id UUID,
            embedding VECTOR(768),
            embedding_model TEXT,
            confidence REAL NOT NULL DEFAULT 0.5 CHECK (confidence BETWEEN 0 AND 1),
            privacy_level knowledge.privacy_level NOT NULL DEFAULT 'internal',
            layer knowledge.layer NOT NULL DEFAULT 'raw',
            version INT NOT NULL DEFAULT 1,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute(
        "CREATE INDEX node_metadata_embedding_hnsw ON knowledge.node_metadata "
        "USING hnsw (embedding vector_cosine_ops) WHERE embedding IS NOT NULL"
    )
    op.execute("CREATE INDEX node_metadata_label_idx ON knowledge.node_metadata (label)")
    op.execute(
        "CREATE INDEX node_metadata_scope_idx ON knowledge.node_metadata "
        "(scope, project_id, user_id)"
    )
    op.execute("CREATE INDEX node_metadata_layer_idx ON knowledge.node_metadata (layer)")

    op.execute(
        """
        CREATE TABLE knowledge.source_attribution (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            node_id TEXT NOT NULL REFERENCES knowledge.node_metadata(node_id) ON DELETE CASCADE,
            source_type TEXT NOT NULL,
            source_ref TEXT,
            excerpt TEXT,
            confidence_contribution REAL,
            recorded_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute(
        "CREATE INDEX source_attribution_node_idx ON knowledge.source_attribution (node_id)"
    )

    op.execute(
        """
        CREATE TABLE knowledge.node_version_history (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            node_id TEXT NOT NULL,
            version INT NOT NULL,
            change_type TEXT NOT NULL,
            previous_value JSONB,
            new_value JSONB,
            changed_by TEXT NOT NULL,
            changed_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute(
        "CREATE INDEX node_version_history_node_idx ON knowledge.node_version_history "
        "(node_id, version)"
    )

    op.execute(
        """
        CREATE TABLE knowledge.contradiction (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            node_a_id TEXT NOT NULL,
            node_b_id TEXT NOT NULL,
            description TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'open',
            resolution TEXT,
            detected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            resolved_at TIMESTAMPTZ
        )
        """
    )
    op.execute("CREATE INDEX contradiction_status_idx ON knowledge.contradiction (status)")

    op.execute(
        """
        CREATE TABLE knowledge.node_usage (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            node_id TEXT NOT NULL,
            project_id UUID,
            recorded_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute("CREATE INDEX node_usage_node_idx ON knowledge.node_usage (node_id)")

    op.execute(
        """
        CREATE TABLE knowledge.outbox_event (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            subject TEXT NOT NULL,
            payload JSONB NOT NULL,
            correlation_id UUID NOT NULL,
            causation_id UUID,
            graph_write JSONB,
            graph_applied_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            dispatched_at TIMESTAMPTZ
        )
        """
    )
    op.execute(
        "CREATE INDEX outbox_undispatched_idx ON knowledge.outbox_event (created_at) "
        "WHERE dispatched_at IS NULL"
    )
    op.execute(
        "CREATE INDEX outbox_graph_pending_idx ON knowledge.outbox_event (created_at) "
        "WHERE graph_write IS NOT NULL AND graph_applied_at IS NULL"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS knowledge.outbox_event")
    op.execute("DROP TABLE IF EXISTS knowledge.node_usage")
    op.execute("DROP TABLE IF EXISTS knowledge.contradiction")
    op.execute("DROP TABLE IF EXISTS knowledge.node_version_history")
    op.execute("DROP TABLE IF EXISTS knowledge.source_attribution")
    op.execute("DROP TABLE IF EXISTS knowledge.node_metadata")
    op.execute("DROP TYPE IF EXISTS knowledge.privacy_level")
    op.execute("DROP TYPE IF EXISTS knowledge.layer")
    op.execute("DROP SCHEMA IF EXISTS knowledge CASCADE")
