"""Initial agent_os schema

Revision ID: 0001
Revises:
Create Date: 2026-08-23

Matches docs/design/phase-3/08-tdd-3e-agent-os.md §4 exactly (the
`agent_instance` table only -- `agent_package`, TDD 3E §5, is
`agent-os/registry`'s own table, added by that component's own migration
once it exists). Hand-written rather than autogenerated, the same
convention as every prior engine's initial migration.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS agent_os")

    op.execute(
        """
        CREATE TABLE agent_os.agent_instance (
            id                      UUID PRIMARY KEY,
            agent_package_id        UUID NOT NULL,
            category                TEXT NOT NULL,
            execution_backend       TEXT NOT NULL,
            status                  TEXT NOT NULL,
            assigned_task_node_id   UUID,
            supervisor_id           UUID,
            started_at              TIMESTAMPTZ NOT NULL,
            health_status           TEXT NOT NULL DEFAULT 'unknown'
        )
        """
    )
    op.execute(
        "CREATE INDEX agent_instance_status_idx ON agent_os.agent_instance (status)"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS agent_os.agent_instance")
    op.execute("DROP SCHEMA IF EXISTS agent_os")
