"""Append-only agent_activity table

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-08

Phase 4C milestone 4C.2b. Adds the Kernel-owned, append-only
`agent_os.agent_activity` table that later slices read through
`GET /v1/agents/{id}/activity` (4C.2c) and write from the existing dispatch
and reconciliation paths (4C.2d). Hand-written rather than autogenerated,
the same convention as `0001_initial_schema.py` and every prior engine.

Notes on the shape, each of which is a decision rather than a default:

* **No `DEFAULT now()` on `occurred_at`.** Postgres `now()` is transaction-
  start time, so every row written in one transaction would share a
  timestamp -- precisely the tie the `(occurred_at DESC, id DESC)` ordering
  has to break. The value is supplied by Python
  (`domain/activity.py::new_activity`).
* **A real foreign key.** `agent_instance.agent_package_id` has none because
  it points at `agent-os/registry`'s table across a component boundary
  (see `repository/models.py`); this points at a table this component owns
  and migrates in the same chain, so the constraint costs nothing and buys
  integrity. `ON DELETE` is deliberately omitted: nothing deletes an
  `agent_instance`, and declaring a cascade would describe a deletion path
  that does not exist.
* **A `CHECK` on `kind`.** The domain enum already rejects an unknown kind,
  but only for callers going through the Pydantic model. The constraint
  makes the closed vocabulary true of the table itself.
* **`correlation_id` is a nullable column, not a JSON key.** It is the join
  key that makes "reasoning -> plan -> instance -> activity -> peer review" a
  traversable chain, so it is typed and queryable rather than buried in
  `detail`. Nullable and with **no default**: `NULL` truthfully means "no
  correlation is known", where a generated value would manufacture provenance
  that links nothing. It is deliberately absent from the index below -- a
  join key, not an ordering key.
* **The index matches the query exactly** -- `(agent_instance_id,
  occurred_at DESC, id DESC)` is the keyset predicate and the ORDER BY of
  `list_activity`, so paging is an index scan rather than a sort.
  `correlation_id` is not in it, and the ordering does not change.

The downgrade drops only this table. `0001`'s downgrade owns the schema; a
`DROP SCHEMA` here would take `agent_instance` -- and `agent-os/registry`'s
`agent_package`, which shares the `agent_os` schema -- with it.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None

#: Mirrors `domain.activity.AgentActivityKind`. Spelled out rather than
#: imported: a migration records the schema as it was applied, and must not
#: change retroactively when the enum gains a member. A later kind arrives
#: with its own migration altering this constraint.
_KINDS = (
    "dispatched",
    "completed",
    "failed",
    "restart_planned",
    "interrupted",
    "peer_review",
)


def upgrade() -> None:
    kinds = ", ".join(f"'{kind}'" for kind in _KINDS)
    op.execute(
        f"""
        CREATE TABLE agent_os.agent_activity (
            id                  UUID PRIMARY KEY,
            agent_instance_id   UUID NOT NULL
                                REFERENCES agent_os.agent_instance (id),
            occurred_at         TIMESTAMPTZ NOT NULL,
            kind                TEXT NOT NULL,
            correlation_id      UUID,
            detail              JSONB NOT NULL DEFAULT '{{}}',
            CONSTRAINT ck_agent_activity_kind CHECK (kind IN ({kinds}))
        )
        """
    )
    op.execute(
        """
        CREATE INDEX agent_activity_instance_time_idx
            ON agent_os.agent_activity (agent_instance_id, occurred_at DESC, id DESC)
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS agent_os.agent_activity")
