"""Observability instruments -- docs/architecture/15-development-workflow.md §9
item 10.

`create_metrics()` must only be called *after* `configure_observability()` has
run, mirroring `nova-core`'s `HeartbeatPublisher` and Memory/Knowledge Engine's
own `observability.py` modules. `api/` and `workers/` read the resulting
instruments off `app.state.metrics` / a passed-in `WorldModelEngineMetrics`;
`domain/` never imports this module.
"""

from __future__ import annotations

from dataclasses import dataclass

from nova_observability import get_meter
from opentelemetry.metrics import Counter, Histogram


@dataclass(frozen=True)
class WorldModelEngineMetrics:
    context_request_duration_seconds: Histogram
    """Latency of `world_model.context.request` -- the tightest budget in
    Phase 1 (p95 < 20ms, §15): every Thinking Pipeline execution calls it."""

    object_write_duration_seconds: Histogram
    """Latency of `domain.object_graph.observe_object`'s Postgres-side write,
    excluding async graph apply."""

    fusion_window_duration_seconds: Histogram

    context_requests_total: Counter

    context_degraded_total: Counter
    """Context requests where Redis (the primary store) was unreachable --
    §17: fails fast, never silently returns stale/empty context."""

    objects_observed_total: Counter
    """Labeled by `outcome` (`created` | `updated`)."""

    objects_removed_total: Counter

    conflicts_resolved_total: Counter
    """Labeled by `strategy` (`confidence` | `recency` | `policy` |
    `unresolved`)."""

    attention_boosts_total: Counter

    predictions_generated_total: Counter

    snapshots_taken_total: Counter
    """Labeled by `trigger` (`scheduled` | `manual` | `pre_risky_action`)."""

    graph_writes_applied_total: Counter
    """Neo4j writes applied by the saga dispatcher's step 2 (§17)."""

    outbox_dispatched_total: Counter
    """Labeled by `subject`."""

    graph_write_degraded_total: Counter
    """Outbox rows found still pending their Neo4j write past
    `Settings.graph_write_degraded_threshold_minutes` (§17 step 4)."""


def create_metrics() -> WorldModelEngineMetrics:
    meter = get_meter("world-model-engine")
    return WorldModelEngineMetrics(
        context_request_duration_seconds=meter.create_histogram(
            "world_model_engine_context_request_duration_seconds",
            description="Latency of world_model.context.request.",
            unit="s",
        ),
        object_write_duration_seconds=meter.create_histogram(
            "world_model_engine_object_write_duration_seconds",
            description="Latency of an object observation write, excluding async graph apply.",
            unit="s",
        ),
        fusion_window_duration_seconds=meter.create_histogram(
            "world_model_engine_fusion_window_duration_seconds",
            description="Processing time for one fusion window.",
            unit="s",
        ),
        context_requests_total=meter.create_counter(
            "world_model_engine_context_requests_total",
            description="Active Context reads.",
        ),
        context_degraded_total=meter.create_counter(
            "world_model_engine_context_degraded_total",
            description="Context requests that failed due to Redis unavailability.",
        ),
        objects_observed_total=meter.create_counter(
            "world_model_engine_objects_observed_total",
            description="World Object observations, labeled by outcome.",
        ),
        objects_removed_total=meter.create_counter(
            "world_model_engine_objects_removed_total",
            description="World Objects removed from current reality.",
        ),
        conflicts_resolved_total=meter.create_counter(
            "world_model_engine_conflicts_resolved_total",
            description="Conflicting observations resolved, labeled by strategy.",
        ),
        attention_boosts_total=meter.create_counter(
            "world_model_engine_attention_boosts_total",
            description="Attention boost events applied.",
        ),
        predictions_generated_total=meter.create_counter(
            "world_model_engine_predictions_generated_total",
            description="Environment predictions generated by prediction_worker.",
        ),
        snapshots_taken_total=meter.create_counter(
            "world_model_engine_snapshots_taken_total",
            description="World State Snapshots taken, labeled by trigger.",
        ),
        graph_writes_applied_total=meter.create_counter(
            "world_model_engine_graph_writes_applied_total",
            description="Neo4j writes applied by the saga dispatcher.",
        ),
        outbox_dispatched_total=meter.create_counter(
            "world_model_engine_outbox_dispatched_total",
            description="Outbox events dispatched to the Event Bus, labeled by subject.",
        ),
        graph_write_degraded_total=meter.create_counter(
            "world_model_engine_graph_write_degraded_total",
            description="Outbox rows stuck pending a Neo4j write past the degraded threshold.",
        ),
    )
