"""Initial planning schema

Revision ID: 0001
Revises:
Create Date: 2026-08-20

Matches docs/design/phase-3/05-tdd-3b-planning-engine.md §4 exactly.
Hand-written rather than autogenerated, the same convention as every prior
engine's initial migration (e.g. `action-engine`'s).
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS planning")

    op.execute(
        """
        CREATE TABLE planning.task_graph (
            id               UUID PRIMARY KEY,
            root_objective   TEXT NOT NULL,
            critical_path    JSONB NOT NULL DEFAULT '[]',
            approved_at      TIMESTAMPTZ,
            created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )

    op.execute(
        """
        CREATE TABLE planning.task_node (
            id                          UUID PRIMARY KEY,
            task_graph_id               UUID NOT NULL REFERENCES planning.task_graph (id),
            objective                   TEXT NOT NULL,
            depends_on                  JSONB NOT NULL DEFAULT '[]',
            assigned_agent_category     TEXT,
            estimated_effort            JSONB NOT NULL,
            risk                        TEXT NOT NULL,
            status                      TEXT NOT NULL DEFAULT 'pending',
            created_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at                  TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute(
        "CREATE INDEX task_node_task_graph_idx ON planning.task_node (task_graph_id)"
    )

    op.execute(
        """
        CREATE TABLE planning.outbox_event (
            id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            subject          TEXT NOT NULL,
            payload          JSONB NOT NULL,
            correlation_id   UUID NOT NULL,
            causation_id     UUID,
            created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
            dispatched_at    TIMESTAMPTZ
        )
        """
    )
    op.execute(
        "CREATE INDEX outbox_undispatched_idx ON planning.outbox_event (created_at) "
        "WHERE dispatched_at IS NULL"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS planning.outbox_event")
    op.execute("DROP TABLE IF EXISTS planning.task_node")
    op.execute("DROP TABLE IF EXISTS planning.task_graph")
    op.execute("DROP SCHEMA IF EXISTS planning")
