"""Initial executive schema

Revision ID: 0001
Revises:
Create Date: 2026-08-06

Matches docs/design/phase-2c/00-executive-cognition-engine.md §19 exactly.
Hand-written rather than autogenerated, the same convention as every prior
engine's initial migration. No `graph_write`/`graph_applied_at` columns on
`outbox_event` -- this engine owns no graph.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS executive")

    op.execute(
        """
        CREATE TABLE executive.executive_request (
            correlation_id UUID PRIMARY KEY,
            requesting_engine TEXT NOT NULL,
            request_kind TEXT NOT NULL,
            user_id UUID NOT NULL,
            urgency DOUBLE PRECISION NOT NULL,
            importance DOUBLE PRECISION NOT NULL,
            complexity DOUBLE PRECISION NOT NULL,
            risk DOUBLE PRECISION NOT NULL,
            learning_value DOUBLE PRECISION NOT NULL,
            resource_cost DOUBLE PRECISION NOT NULL,
            user_impact DOUBLE PRECISION NOT NULL,
            deadline TIMESTAMPTZ,
            goal_id UUID,
            goal_tier TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute(
        "CREATE INDEX executive_request_goal_idx ON executive.executive_request (goal_id)"
    )
    op.execute(
        "CREATE INDEX executive_request_user_idx ON executive.executive_request (user_id)"
    )
    op.execute(
        "CREATE INDEX executive_request_created_idx ON executive.executive_request (created_at)"
    )

    op.execute(
        """
        CREATE TABLE executive.executive_decision (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            correlation_id UUID NOT NULL,
            requesting_engine TEXT NOT NULL,
            decision_type TEXT NOT NULL,
            outcome TEXT NOT NULL,
            trace_payload JSONB NOT NULL,
            schema_version INTEGER NOT NULL DEFAULT 1,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute(
        "CREATE INDEX executive_decision_correlation_idx ON executive.executive_decision "
        "(correlation_id)"
    )
    op.execute(
        "CREATE INDEX executive_decision_requesting_engine_idx ON executive.executive_decision "
        "(requesting_engine)"
    )
    op.execute(
        "CREATE INDEX executive_decision_created_idx ON executive.executive_decision (created_at)"
    )

    op.execute(
        """
        CREATE TABLE executive.executive_outcome_report (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            correlation_id UUID NOT NULL REFERENCES executive.executive_request(correlation_id),
            outcome TEXT NOT NULL,
            actual_duration_ms DOUBLE PRECISION,
            note TEXT,
            schema_version INTEGER NOT NULL DEFAULT 1,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute(
        "CREATE INDEX executive_outcome_report_correlation_idx ON "
        "executive.executive_outcome_report (correlation_id)"
    )

    op.execute(
        """
        CREATE TABLE executive.human_override (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            executive_decision_id UUID NOT NULL REFERENCES executive.executive_decision(id),
            action TEXT NOT NULL,
            redirect_outcome TEXT,
            note TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute(
        "CREATE INDEX human_override_decision_idx ON executive.human_override "
        "(executive_decision_id)"
    )

    op.execute(
        """
        CREATE TABLE executive.outbox_event (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            subject TEXT NOT NULL,
            payload JSONB NOT NULL,
            correlation_id UUID NOT NULL,
            causation_id UUID,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            dispatched_at TIMESTAMPTZ
        )
        """
    )
    op.execute(
        "CREATE INDEX outbox_undispatched_idx ON executive.outbox_event (created_at) "
        "WHERE dispatched_at IS NULL"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS executive.outbox_event")
    op.execute("DROP TABLE IF EXISTS executive.human_override")
    op.execute("DROP TABLE IF EXISTS executive.executive_outcome_report")
    op.execute("DROP TABLE IF EXISTS executive.executive_decision")
    op.execute("DROP TABLE IF EXISTS executive.executive_request")
    op.execute("DROP SCHEMA IF EXISTS executive CASCADE")
