"""Initial autonomy schema

Revision ID: 0001
Revises:
Create Date: 2026-09-13

`autonomy.decision_log` matches docs/architecture/07-data-architecture.md's
canonical definition; the other four tables match
docs/design/phase-4/04-tdd-4d-autonomy-engine.md §9. Hand-written rather than
autogenerated, the same convention as every prior engine's initial migration.

**Additive only.** This migration creates a new schema and touches no existing
engine's tables. `action.identity_confidence_policy` in particular is untouched
in structure *and* in content -- 4D writes no policy row (TDD §11, D-4D-2).
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS autonomy")

    op.execute(
        """
        CREATE TABLE autonomy.autonomy_level (
            user_id     UUID PRIMARY KEY,
            level       SMALLINT NOT NULL,
            updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )

    op.execute(
        """
        CREATE TABLE autonomy.policy (
            id                      UUID PRIMARY KEY,
            user_id                 UUID NOT NULL,
            name                    TEXT NOT NULL,
            effect                  TEXT NOT NULL,
            match_category          TEXT,
            match_min_risk          TEXT,
            match_capability_class  TEXT,
            enabled                 BOOLEAN NOT NULL DEFAULT true,
            created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at              TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute("CREATE INDEX ix_policy_user_id ON autonomy.policy (user_id)")

    # A category with no row is the fail-closed default (TDD §7): this table is
    # expected to be sparse and is never backfilled with permissive defaults.
    op.execute(
        """
        CREATE TABLE autonomy.permission_grant (
            user_id                  UUID NOT NULL,
            category                 TEXT NOT NULL,
            max_risk                 TEXT,
            requires_approval_above  TEXT,
            updated_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
            PRIMARY KEY (user_id, category)
        )
        """
    )

    op.execute(
        """
        CREATE TABLE autonomy.suggestion (
            id          UUID PRIMARY KEY,
            user_id     UUID NOT NULL,
            category    TEXT NOT NULL,
            risk        TEXT NOT NULL,
            title       TEXT NOT NULL,
            detail      TEXT NOT NULL DEFAULT '',
            status      TEXT NOT NULL DEFAULT 'proposed',
            created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
            decided_at  TIMESTAMPTZ
        )
        """
    )
    # Keyset pagination on (created_at DESC, id DESC) -- no offset anywhere
    # (TDD §8.1/§9). The `id` tiebreaker makes a page boundary deterministic
    # when two suggestions share a timestamp.
    op.execute(
        """
        CREATE INDEX ix_suggestion_user_created_id
            ON autonomy.suggestion (user_id, created_at DESC, id DESC)
        """
    )
    op.execute(
        "CREATE INDEX ix_suggestion_user_status ON autonomy.suggestion (user_id, status)"
    )

    # Doc 07's canonical table. `action_id` keeps doc 07's column name; 4D
    # writes the decision's own subject id into it because 4D creates no
    # Action (the action-engine boundary, TDD §8.1).
    #
    # `suggestion_id` is the foreign key 4C.2's `4eafa80` defect is the reason
    # for: ON DELETE RESTRICT, never CASCADE, so deleting a suggestion cannot
    # erase the record of the decision that produced it. The log is
    # append-only -- no repository method updates or deletes a row here.
    op.execute(
        """
        CREATE TABLE autonomy.decision_log (
            id              UUID PRIMARY KEY,
            action_id       UUID NOT NULL,
            suggestion_id   UUID REFERENCES autonomy.suggestion (id) ON DELETE RESTRICT,
            autonomy_level  SMALLINT NOT NULL,
            risk            TEXT NOT NULL,
            confidence      REAL NOT NULL,
            policy_checks   JSONB NOT NULL DEFAULT '[]',
            outcome         TEXT,
            reason          TEXT,
            created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute("CREATE INDEX ix_decision_log_action_id ON autonomy.decision_log (action_id)")
    op.execute(
        """
        CREATE INDEX ix_decision_log_created_id
            ON autonomy.decision_log (created_at DESC, id DESC)
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS autonomy.decision_log")
    op.execute("DROP TABLE IF EXISTS autonomy.suggestion")
    op.execute("DROP TABLE IF EXISTS autonomy.permission_grant")
    op.execute("DROP TABLE IF EXISTS autonomy.policy")
    op.execute("DROP TABLE IF EXISTS autonomy.autonomy_level")
    op.execute("DROP SCHEMA IF EXISTS autonomy")
