"""Initial agent_os schema (registry's own table)

Revision ID: 0001
Revises:
Create Date: 2026-08-23

Matches the approved Fork 3E-2 concrete ORM shape
(docs/design/phase-3/14-3e-agent-os-research.md §4), corrected from this
migration's own original `(id, version)` composite primary key -- see
docs/design/phase-3/15-3e-supervisor-reconciliation.md §A. `agent_instance`
(TDD 3E §4) is `agent-os/kernel`'s own table, added by that component's
own migration, already merged in Phase 3E Milestone 2. Hand-written rather
than autogenerated, the same convention as every prior engine's initial
migration.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS agent_os")

    op.execute(
        """
        CREATE TABLE agent_os.agent_package (
            id                                      UUID NOT NULL PRIMARY KEY,
            category                                TEXT NOT NULL,
            version                                 TEXT NOT NULL,
            manifest_json                           JSONB NOT NULL,
            installed_at                            TIMESTAMPTZ NOT NULL,
            health_status                           TEXT NOT NULL DEFAULT 'unknown',
            checksum                                TEXT NOT NULL,
            supervisor_notified_new_permissions     JSONB NOT NULL DEFAULT '[]',
            CONSTRAINT uq_agent_package_category_version UNIQUE (category, version)
        )
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS agent_os.agent_package")
    op.execute("DROP SCHEMA IF EXISTS agent_os")
